In [2]:
with open('punarchi.txt', 'r+', encoding= 'utf-8') as f:
    contents = f.read()

print(contents)

பலபல => பல+பல
சிலசில => சில+சில
பலப்பல => பல+பல
சிலச்சில => சில+சில
பலற்பல => பல+பல
சிலற்சில => சில+சில
பல்கலை => பல+கலை
பல்சாலை => பல+சாலை
பஃதொடை => பல+தொடை
பன்மலர் => பல+மலர்
பன்னாடு => பல+நாடு
பல்வேண்டி => பல+வேண்டி
பல்லரண் => பல+அரண்
சில்சொல் => சில+சொல்
சின்மலர் => சில+மலர்
சில்வளை => சில+வளை
சில்லணி => சில+அணி
வடகிழக்கு => வடக்கு+கிழக்கு
வடமேற்கு => வடக்கு+மேற்கு
வடவேங்கடம் => வடக்கு+வேங்கடம்
குடதிசை => குடக்கு+திசை
குணதிசை => குணக்கு+திசை
தென்கிழக்கு => தெற்கு+கிழக்கு
தென்மேற்கு => தெற்கு+மேற்கு
தென்குமரி => தெற்கு+குமரி
தென்பாண்டி => தெற்கு+பாண்டி
மேல்காற்று => மேற்கு+காற்று
மேலூர் => மேற்கு+ஊர்
கீழ்கடல் => கிழக்கு+கடல்
கீழ்நாடு => கிழக்கு+நாடு
நல்லன் => நன்மை+அன்
வெண்பட்டு => வெண்மை+பட்டு
வெண்குடை => வெண்மை+குடை
செம்மலர் => செம்மை+மலர்
பெரியன் => பெருமை+அன்
சிறியன் => சிறுமை+அன்
மூதூர் => முதுமை+ஊர்
பாசி => பசுமை+இ
பைங்கொடி => பசுமை+கொடி
பைந்தார் => பசுமை+தார்
சிற்றூர் => சிறுமை+ஊர்
வெற்றிலை => வெறுமை+இலை
வெவ்வேல் => வெம்மை+வேல்
வெந்நீர் => வெம்மை+நீர்
செங்கோல் => செம்மை+கோல்
செந்தமிழ் => செம்மை+தமிழ்
பேரூர் => பெருமை+ஊர்
பைம்பொழில் => பசுமை+பொழில்
தமிழாசிரியர் => தமிழ்+ஆசிரியர்
கடவுளருள் => கடவுள்+அருள்
பொருளனைத்தும் => பொருள்+அனைத்தும்
பூங்கொடி => பூ+கொடி
பூஞ்சோலை => பூ+சோலை
பூந்தோட்டம் => பூ+தோட்டம்
பூம்பாவை => பூ+பாவை
கண்ணொளி => கண்+ஒளி
பண்ணோசை => பண்+ஓசை
மண்ணோசை => மண்+ஓசை
மணியடித்தது => மணி+அடித்தது
தீயெரிந்தது => தீ+எரிந்தது
வாழையிலை => வாழை+இலை
நிலாவழகு => நிலா+அழகு
சேயழகு => சே+அழகு
சேவழகு => சே+அழகு
அந்தப்பையன் => அந்த+பையன்
இந்தப்பெட்டி => இந்த+பெட்டி
அத்துணைப் புகழ் => அத்துணை+புகழ்
இத்துணைச் செழுமை => இத்துணை+செழுமை
எத்துணைக் கொடுமை => எத்துணை+கொடுமை
அவ்வகைக்காடு => அவ்வகை+காடு
இவ்வகைத்தோப்பு => இவ்வகை+தோப்பு
எவ்வகைப்பெயர் => எவ்வகை+பெயர்
மற்றக்கலைகள் => மற்ற+கலைகள்
மற்றுச்சிலை => மற்ற+சிலை
மற்றைப்பயன் => மற்றை+பயன்
மோர்க்குடம் => மோர்+குடம்
மலர்க்கூந்தல் => மலர்+கூந்தல்
தயிர்ப்பானை => தயிர்+பானை
தண்ணீர்த்தொட்டி => தண்ணீர்+தொட்டி
மரப்பெட்டி => மரம்+பெட்டி
இரும்புத்தூண் => இரும்பு+தூண்
தங்கத்தாலி => தங்கம்+தாலி
குடைக்கம்பி => குடை+கம்பி
சட்டைத்துணி => சட்டை+துணி
அடுப்புப்புகை => அடுப்பு+புகை
விழிப்புனல் => விழி+புனல்
புதுக்குடம் => புது+குடம்
வட்டப்பலகை => வட்டம்+பலகை
பொய்ச்செய்தி => பொய்+செய்தி
வேழக்கரும்பு => வேழம்+கரும்பு
தாமரைப்பூ => தாமரை+பூ
மார்கழித்திங்கள் => மார்கழி+திங்கள்
தாமரைக்கண்ணன் => தாமரை+கண்ணன்
பவளச்செவ்வாய் => பவளம்+செவ்வாய்
மலைத்தோள் => மலை+தோள்
அரைக்காணி => அரை+காணி
அரைப்படி => அரை+படி
பாதிப்பங்கு => பாதி+பங்கு
அரைத்தொட்டி => அரை+தொட்டி
பாதிச்செலவு => பாதி+செலவு
திருக்கோவில் => திரு+கோவில்
புதுப்புது => புது+புது
பொதுச்சாலை => பொது+சாலை
வினாக்குறி => வினா+குறி
பலாப்பழம் => பலா+பழம்
கருத்தாய்க்கேட்டாள் => கருத்தாய்+கேட்டாள்
அன்பாய்ச்சொன்னார் => அன்பாய்+சொன்னார்
போய்ப்பார் => போய்+பார்
முன்னர்க்கண்டோம் => முன்னர்+கண்டோம்
பின்னர்க்காண்போம் => பின்னர்+காண்போம்
முன்னர்ச்செல்க => முன்னர்+செல்க
பின்னர்ப்பணிந்தார் => பின்னர்+பணிந்தார்
பட்டுச்சேலை => பட்டு+சேலை
பத்துப்பாட்டு => பத்து+பாட்டு
அவ்வளவுபெரிது => அவ்வளவு+பெரிது
இவ்வளவு கனிவா? => இவ்வளவு+கனிவா
எவ்வளவு தொலைவு? => எவ்வளவு+தொலைவு
அத்தனை புத்தகங்களா? => அத்துணை+புத்தகங்களா
இத்தனை தொழில்களா? => இத்துணை+தொழில்களா
எத்தனை கருவிகள்? => எத்துணை+கருவிகள்
அவனா கேட்டான்? => அவனா+கேட்டான்
அவளா சொன்னாள்? => அவளா+சொன்னாள்
யாரே கண்டார்? => யாரே+கண்டார்
பெரிய பெண் => பெரிய+பெண்
கற்ற சிறுவன் => கற்ற+சிறுவன்
நில்லாத செல்வம் => நில்லாத+செல்வம்
அழியாத கல்வி => அழியாத+கல்வி
ஒன்று கேள் => ஒன்று+கேள்
ஒரு பொருள் => ஒரு+பொருள்
இரண்டு புத்தகம் => இரண்டு+புத்தகம்
இரு பறவை => இரு+பறவை
மூன்று குறிக்கோள் => மூன்று+குறிக்கோள்
நான்கு பேர் => நான்கு+பேர்
ஐந்து கதைகள் => ஐந்து+கதைகள்
ஆறு கோவில் => ஆறு+கோவில்
அறுசீர் => அறு+சீர்
ஏழு சான்றுகள் => ஏழு+சான்றுகள்
எழு பிறப்பு => ஏழு+பிறப்பு
ஒன்பது சுவைகள் => ஒன்பது+சுவைகள்
கலகல => கல+கல
சடசட => சட+சட
பளபள => பள+பள
தீதீ => தீ+தீ
பார்பார் => பார்+பார்
கற்க கசடற => கற்க+கசடற
வெல்க தமிழ் => வெல்க+தமிழ்
வீழ்க தண்புனல் => வீழ்க+தண்புனல்
பல பசு => பல+பசு
சில கலை => சில+கலை
அவை தவித்தன => அவை+தவித்தன
வா கலையரசி => வா+கலையரசி
எழு தம்பி => எழு+தம்பி
போ செல்வி => போ+செல்வி
பார் பெண்ணே => பார்+பெண்ணே
கோவலனோடு கண்ணகி வந்தாள் => கோவலனோடு+கண்ணகி வந்தாள்
துணிவோடு செல்க => துணிவோடு+செல்க
அண்ணனோடு தங்கை வந்தாள் => அண்ணனோடு+தங்கை வந்தாள்
காணிய சென்றேன் => காணிய+சென்றேன்
உண்ணிய சென்றாள் => உண்ணிய+சென்றாள்
தாய் கண்டாள் => தாய்+கண்டாள்
விரிசுடர் => விரி+சுடர்
பாய்புலி => பாய்+புலி
காய்கனி => காய்+கனி
தாய்தந்தை => தாய்+தந்தை
அது பறந்தது => அது+பறந்தது
இது கடித்தது => இது+கடித்தது
எது பறந்தது? => எது+பறந்தது
யாது தந்தார்? => யாது+தந்தார்
கண்ணா பாடு => கண்ணா+பாடு
அண்ணா கேள் => அண்ணா+கேள்
எழுத்துகள் => எழுத்து+கள்
கருத்துகள் => கருத்து+கள்
வாழ்த்துகள் => வாழ்த்து+கள்
போற்றுதல் => போற்று+தல்
நொறுக்குதல் => நொறுக்கு+தல்
கோஷ்டி கானம் => கோஷ்டி+கானம்
சங்கீத சபா => சங்கீத+சபா
வாழைப்பழம் => வாழை+பழம்
மாமரம் => மா+மரம்
அவரைக்காய் => அவரை+காய்
மட்குடம் => மண்+குடம்
மரவேர் => மரம்+வேர்
பெருவள்ளல் => பெருமை+வள்ளல்
பெருநன்மை => பெருமை+நன்மை
மணியழகு => மணி+அழகு
கருத்தோடிசைந்து => கருத்தோடு+இசைந்து
பயணங்கள் => பயணம்+கள்
ஆதாரக்கோடுகள் => ஆதாரம்+கோடுகள்
உருவெடுத்துள்ளன => உருவ+உடுத்துள்ளன
இசைக்கருவி => இசை+கருவி
துளைக்கருவிகள் => துளை+கருவிகள்
சக்கரங்கள் => சக்கர+கள்
கருங்கடல் => கரு+கடல்
நவீனக்கதையாக => நவீன+கதை+ஆக
சிவந்த => சிவப்பு+நடை
இருட்டுக்குள் => இருட்டு+குள்
கரும்புத் => கரும்பு+த்
துயரக்காற்று => துயரம்+காற்று
இயற்பியல் => இயல்+பியல்
கேலக்ஸி => கலை+க்ஸி
கள்ளுக்கடை => கள்ளு+கடை
மதுரக்கள்ளு => மதுரை+க்கள்ளு
பக்கங்கள் => பக்கம்+கள்
இறந்துவிட்ட => இறந்த+விட்ட
இக்கதையை => இந்த+கதை+ஐ
விளக்குகள் => விளக்கு+கள்
ஸிரசாத்தும் => ஸிரசா+த்தும்
இருளில் => இருள்+இல்
பயணித்துக் => பயணம்+இத்து+க
நாடகக்குழு => நாடகம்+குழு
அப்பணசாமி => அப்பன்+சாமி
வள்ளிதிருமணம் => வள்ளி+திருமணம்
நடக்கும் => நட+க்கும்
இலக்கணம் => இலக்கு+ணம்
நாடகக்காரர்கள் => நாடகம்+காரர்கள்
மறந்துபோய் => மறந்த+போய்
நகரும் => நகர்+ும்
இருக்கிறார்கள் => இருக்க+ிறார்கள்
பயணித்த => பயணம்+இத்து
கிழக்கில் => கிழக்கு+இல்
பக்கத்தில் => பக்கம்+இல்
சீறிவரும் => சீறும்+வரும்
ஊருமே => ஊர்+உமே
இறந்துபோன => இறந்த+போன
குழந்தையின் => குழந்தை+இன்
ஒன்றுகலந்து => ஒன்று+கலந்து
அக்கார்டியன் => அக்கார்ட்+டியன்
கந்தசாமி => கந்த+சாமி+இன்
வெளிவந்த => வெளியே+வந்த
பாட்டக்குளம் => பாட்டு+குளம்
இருமுனை => இரு+முனை
இயற்கையின் => இயற்கை+இன்
மயக்கமுறும் => மயக்கம்+முறும்
இயலாமையின் => இயலாமை+இன்
உருக்கம் => உரு+க்கம்
சரவணக்குமார் => சரவணன்+குமார்
கிடக்கும் => கிடைக்க+ும்
இருக்கும் => இருக்க+ும்
இக்கதை => இந்த+கதை
இருட்டு => இருள்+ட்டு
ஜெயந்தன் => ஜெய+ந்தன்
வந்துசெல்கிறது => வந்த+செல்கிறது
ஜெயந்தனின் => ஜெயந்தன்+இன்
வரும் => வர+ும்
இருவர் => இரு+வர
இருந்துவரும் => இருந்த+வரும்
சம்பந்தமில்லாமல் => சம்பந்த+மில்லாமல்
இருந்தது => இருந்த+து
மையமிழந்து => மையம்+அழந்து
கணக்கியலை => கணக்கு+கலை
சந்தித்துக்கொண்ட => சந்தி+த்துக்கொண்ட
சந்தர்ப்பங்கள் => சந்தர்ப்பு+கள்
உருமாறி => உரு+மாறி
கொலைவழக்கு => கொலை + வழக்கு
வெளிவந்த => வெளி + வந்த
விளக்கைச் => விளக்கு + இச்
இறக்கைகள் => இறக்கு + கைகள்
இருப்பில் => இருப்பு + இல்
இருள் => இருள் + டைப்
துலக்கமான => துலக்கம் + மான
வந்துவிட்டான் => வந்த + விட்டான்
அந்நியமான => அந்நிய + மான
இருந்தார்கள் => இருந்த + அர்கள்
இருக்கிறது => இருக்க + இரு
சிலந்தியின் => சிலந்தி + இன்
பலாச்சுளை => பலா+சுளை
படக்காட்சி => படம்+காட்சி
பொற்சிலை => பொன்+சிலை
பொன்வளையல் => பொன்+வளையல்
கண்ணழகு => கண்+அழகு
மலர்மாலை => மலர்+மாலை
பனைமரம் => பனை+மரம்
மரவேர் => மரம் + வேர்
செந்தமிழ் => செம் + தமிழ்
பஞ்சகத்தி => பஞ்சம் + கத்தி
மெய்யாளர் => மெய் + யாளர்
பழநீர் => பழம் + நீர்
நிலவழி => நிலம் + வழி
வாழ்விடம் => வாழ்வு + இடம்
சிந்தனை => சிது + தனை
அருங்காட்சி => அரும் + காட்சி
காவலர் => காவல் + லர்
வேறுபாடு => வேறு + பாடு
கண்ணோட்டம் => கண் + நோட்டம்
நீர்வளம் => நீர் + வளம்
நூலாளர் => நூல் + ஆலர்
தங்கம் => தன் + கம்
காய்ச்சல் => காய் + ச்சல்
பாசமயம் => பாசம் + அயம்
தேசாந்திரி => தேசம் + அந்திரி
நல்லாசி => நல் + ஆசி
சிற்றறிவு => சிறு + அறிவு
உள்ளகம் => உள் + லகம்
கனல்நீர் => கனல் + நீர்
சூழ்வளம் => சூழ் + வளம்
வணிகர் => வணிகம் + இர்
புணர்ச்சி => புணர் + ச்சி
வடநாடு => வட + நாடு
பொன்னுலகம் => பொன் + உலகம்
மாடுவாசல் => மாடு + வாசல்
கடல்சாரம் => கடல் + சாரம்
கலந்துரை => கலந்து + உரை
பாடல்சாரம் => பாடல் + சாரம்
வானவெளி => வானம் + வெளி
வீரமணி => வீரம் + மணி
மணியாரும் => மணி + ஆரும்
திடம்கொள் => திடம் + கொள்
புத்தகவாசி => புத்தகம் + வாசி
நூற்காட்சி => நூல் + காட்சி
முரசோலி => முரசு + ஓலி
வேளாண்மை => வேளை + ஆண்மை
செல்வமுறை => செல்வம் + முறை
இலக்கியம் => இலக்கு + இயம்
காதல்மொழி => காதல் + மொழி
அழகுருவி => அழகு + உருவி
பொற்கதை => பொன் + கதை
கொடையரசு => கொடை + அரசு
பணியாளன் => பணி + ஆளன்
விலங்கியல் => விலங்கு + இயல்
விழியார் => விழி + யார்
மண்ணமர் => மண் + அமர்
சாந்தியாழி => சாந்தி + ஆழி
கடல்நகர் => கடல் + நகர
நாட்டியக் கலை => நாட்டியம் + கலை
நிலவந்தி => நிலம் + அந்தி
கூழ்நீர்மை => கூழ் + நீர்மை
சிற்றொழுகு => சிறு + ஒழுகு
முடிவுரை => முடிவு + உரை
சபாநாயகர் => சபை + நாயகர்
வணங்கல் => வணங்கு + அல்
சுயமரியாதை => சுயம் + மரியாதை
கழகத் தலைவர் => கழகம் + தலைவர்
பருவநிலை => பருவம் + நிலை
பசுமைநிலம் => பசுமை + நிலம்
உழவர்மணி => உழவர் + மணி
திரையரங்கு => திரை + அரங்கு
பொன்மாலை => பொன் + மாலை
கவிதைவளம் => கவிதை + வளம்
கவிதைநூல் => கவிதை + நூல்
மரமோடு => மரம் + ஓடு
சந்தனக்கால் => சந்தனம் + காலை
தமிழ்ச் சொல் => தமிழ் + சொல்
தென்னமுது => தென்னம் + முது
கற்கோலம் => கல் + கோலம்
கொடியருவி => கொடி + அருவி
செம்மரம் => செம் + மரம்
நிலவுசுடர் => நிலவு + சுடர்
சொற்பழம் => சொல் + பழம்
நறும்பூ => நறும் + பூ
குடிமகன் => குடி + மகன்
வளம்நிலம் => வளம் + நிலம்
மானுடவளம் => மானுடம் + வளம்
மின்சாரம் => மின் + சாரம்
குமிழ்நீர் => குமிழ் + நீர்
புதுமணம் => புது + மணம்
குடிசொல் => குடி + சொல்
உயிர்வளி => உயிர் + வளி
இலவசநீர் => இலவசம் + நீர்
வள்ளுவர் => வள்ளு + அவர்
சிந்தாமணி => சிந்தை + மணி
வெள்ளநீர் => வெள்ளம் + நீர்
வானளி => வானம் + அளி
கூந்தல் => கூந் + தல்
குளிர்ந்தலை => குளிர் + தலைய
வடசெல்வம் => வட + செல்வம்
அமிழ்தமோர் => அமிழ்தம் + ஓர்
பந்தல் => பந்தம் + அல்
குளம்பேர் => குளம் + பேர்
மாயவரம் => மாயம் + வரம்
அசைவகம் => அசை + வகம்
பற்பலம் => பல + பலம்
வருங்காலம் => வரும் + காலம்
கற்பகமரம் => கற்பகம் + மரம்
நெடுநாள் => நெடு + நாள்
சுடரொளி => சுடர் + ஒளி
ஆற்றொழில் => ஆற்று + தொழில்
பொற்கோவில் => பொன் + கோவில்
வேளாண் => வேலை + ஆண்
மண்ணிடு => மண் + இடு
கதிரோன் => கதிர் + ஓன்
பொருளாதாரம் => பொருள் + ஆதாரம்
பாடசாலை => பாடம் + சாலை
சோலையடை => சோலை + அடை
கொடிக்கொடி => கொடி + கொடி
சிற்றரசு => சிறு + அரசு
கடலோரம் => கடல் + ஓரம்
தென்றல் => தென் + தல்
வீரவிழா => வீரம் + விழா
உணவகம் => உணவு + அகம்
நிழல்வேல் => நிழல் + வேல்
மகிழ்ச்சி => மகிழ் + ச்சி
தங்கவேல் => தங்கம் + வேல்
பிள்ளையார் => பிள்ளை + யார்
மணிமொழி => மணி + மொழி
மணிக்கோல் => மணி + கோல்
வெண்ணெய் => வெண் + நெய்
வானவில் => வானம் + வில்
கொடியிலங்கு => கொடி + இலம் + இங்கு
மரபு வழி => மரபு + வழி
மலர்க்கொடி => மலர் + கொடி
மெய்ப்பொருள் => மெய் + பொருள்
வானொலி => வான் + ஒலி
முத்தமிழ் => முத் + தமிழ்
நுண்கலை => நுண் + கலை
கதிர்கோள் => கதிர் + கோள்
உடனடி => உடன் + அடி
விருட்சம் => விரு + ச்சம்
கலந்தகூட்டம் => கலந்து + கூட்டம்
பரந்தகோலம் => பரந்து + கோலம்
நெடும்பால் => நெடு + பால்
அகிலநிலை => அகிலம் + நிலை
சுவையமை => சுவை + அமை
காற்று நடை => காற்று + நடை
நல்லிணக்கம் => நல் + இணக்கம்
உறவுநிலை => உறவு + நிலை
சாய்க்கோலம் => சாய்க்கு + கோலம்
நிலவறிவு => நிலவு + அறிவு
பொறியியல் => பொறி + இயல்
பணிநிலை => பணி + நிலை
முற்றுமனை => முறை + மனை
நூறாண்டு => நூறு + ஆண்டு
பண்பாளர் => பண்பு + ஆளர்
சீர்திருத்தம் => சீர் + திருத்தம்
வாழ்நிலை => வாழ் + நிலை
மின்வெள்ளம் => மின் + வெள்ளம்
பூமகள் => பூ + மகள்
மனவளம் => மனம் + வளம்
கால்சட்டை => கால் + சட்டை
மாணாக்கர் => மாண் + ஆக்கர்
மலர்ந்தது => மலர் + இந்து
சீதோஷணம் => சீ + தோஷணம்
கடலவன் => கடல் + அவன்
இலக்கணம் => இலக்கு + அணம
தீர்ப்பாசி => தீர்ப்ப + ஆசி
மதிநிலா => மதிலிலா
மன்னவள் => மன்னன் + அவள்
பூங்கொத்து => பூ + கொத்து
மேகமண்டலம் => மேகம் + மண்டலம்
விளக்கொளி => விளக்கு + ஒளி
கதிர்மணி => கதிர் + மணி
பருவமழை => பருவம் + மழை
செந்தோப்பு => செம் + தோப்பு
பேரழகு => பெரு + அழகு
இனியசொல் => இனிய + சொல்
கொடிமரம் => கொடி + மரம்
வான்குடில் => வான் + குடில்
பொற்காலம் => பொன் + காலம்
சுடர்மணி => சுடர் + மணி
நிலமடி => நிலம் + அடி
வெண்மதி => வெண் + மதி
சிற்பகலை => சிற்பம் + கலை
மழைத்துளி => மழை + துளி
சூரியகிரணம் => சூரியன் + கிரணம்
காவேரிநதி => காவிரி + நதி
புத்தர்மலை => புத்தர் + மலை
இனியமனம் => இனிய + மனம்
அடையாளமணி => அடையாளம் + மணி
காவல்துறை => காவல் + துறை
வானவரம்பு => வானம் + வரம்பு
பழமொழி => பழம் + மொழி
முள்ளாங்கொடி => முள்ளான் + கொடி
பனைமரம் => பனை + மரம்
குருதியெழுத்து => குருதி + எழுத்து
படர்கதிர் => படர் + கதிர்
அறிவாளர் => அறிவு + ஆளர்
அன்பரசு => அன்பு + அரசு
ஆறுமுகம் => ஆறு + முகம்
சாந்தவனம் => சாந்தம் + வனம்
நிலமொழி => நிலம் + மொழி
சிறுபிள்ளை => சிறு + பிள்ளை
முத்தானம் => முத்து + ஆனம்
நூல்நயம் => நூல் + நயம்
சோலைமலை => சோலை + மலை
மரம்கொடி => மரம் + கொடி
நிலவொளி => நிலவு + ஒளி
மழைக்கோல் => மழை + கோல்
காற்றுநிலை => காற்று + நிலை
கனிவொளி => கனி + ஒளி
சூரியபாதை => சூரியன் + பாதை
கடல்நுரை => கடல் + நுரை
அறம்வழி => அறம் + வழி
கானல்நிலம் => கானல் + நிலம்
மணியாடை => மணி + ஆடை
செல்வநிலை => செல்வம் + நிலை
பொற்கோடை => பொன் + கோடை
நிலத்தடி => நிலம் + அடி
வாழ்வெழுச்சி => வாழ்வு + எழுச்சி
புதல்வர் => புதல் + வர
புயல்வேகம் => புயல் + வேகம்
சுவைநிலை => சுவை + நிலை
நெஞ்சுரம் => நெஞ்சு + உரம்
இரவுநதி => இரவு + நதி
கலைவளம் => கலை + வளம்
மால்வரை => மால் + வரை
செழியமணி => செழியன் + மணி
கருங்காலி => கரும் + காலி
விளக்குரை => விளக்கு + உரை
காற்றுவளம் => காற்று + வளம்
பழங்கதை => பழம் + கதை
பொற்குழல் => பொன் + குழல்
எழுத்தாளன் => எழுத்து + ஆளன்
கண்ணிழிவு => கண் + இழிவு
தெய்வகதை => தெய்வம் + கதை
அரும்படி => அரும் + படி
ஊர்நிலை => ஊர் + நிலை
மணிச்சுடர் => மணி + சுடர்
செழும்பாடு => செழும் + பாடு
வான்நிலம் => வான் + நிலம்
கனிமொழி => கனி + மொழி
பழனிவேல் => பழனி + வேல்
அமிழ்தாறு => அமிழ்து + ஆறு
வேல்மணி => வேல் + மணி
மருந்தகம் => மருந்து + அகம்
சின்மொழி => சினம் + மொழி
வெறியாள் => வெறி + யாள்
கொடிமாடம் => கொடி + மாடம்
நட்சத்திரவளம் => நட்சத்திரம் + வளம்
மெய்வழி => மெய் + வழி
கதிர்நிழல் => கதிர் + நிழல்
மணியொளி => மணி + ஒளி
செம்மொழி => செம் + மொழி
செம்மணி => செம் + மணி
கடல்படை => கடல் + படை
திருக்கோவில் => திரு + கோவில்
சுடர்மலை => சுடர் + மலை
நளினமணி => நளினம் + மணி
வரலாற்று => வரல் + ஆறு
சீர்மிகு => சீரு + மிகு
பாற்குடம் => பால் + குடம்
செந்தேன் => செம் + தேன்
மண்ணொலி => மண் + ஒலி
விளங்கோலம் => விளம் + கோலம்
மூங்கில் => மூ + கில்
அறந்தலம் => அறம் + தலம்
முல்லைப்பூ => முல்லை + பூ
காற்றுமரம் => காற்று + மரம்
வெள்ளவெண் => வெள்ளம் + வெண்
கடல்சங்கு => கடல் + சங்கு
மண்ணோடு => மண் + ஓடு
உலோகவேல் => உலோகம் + வேல்
பசும்விழி => பசு + விழி
வெண்கோல் => வெண் + கோல்
மண்ணிறம் => மண் + நிறம்
கொடிமலை => கொடி + மலை
கலைமகள் => கலை + மகள்
வண்ணக்குடை => வண்ணம் + குடை
மருந்துவேர் => மருந்து + வேர்
மண்ணறை => மண் + அறை
ஆரண்மனை => ஆரம் + மனை
சுடர்கோல் => சுடர் + கோல்
கொன்றைவனம் => கொன்றை + வனம்
வான்கோலம் => வானம் + கோலம்
கானகத்தேர் => கானகம் + தேர்
கடல்மணி => கடல் + மணி
முற்றவறை => முறை + அறை
வான்சுடர் => வானம் + சுடர்
இருள்வழி => இருள் + வழி
காற்றுவழி => காற்று + வழி
செறியடி => செறி + அடி
குருதிமணல் => குருதி + மணல்
கருங்கூடு => கரும் + கூடு
கனவுயர்வு => கனவு + உயர்வு
எழில்கனி => எழில் + கனி
மருங்கணி => மருங்கு + அணி
மலைவழி => மலை + வழி
கடல்மலை => கடல் + மலை
கதிர்மழை => கதிர் + மழை
மழைமணி => மழை + மணி
பசும்பொன் => பசு + பொன்
மழைத்தேன் => மழை + தேன்
செம்மலர் => செம் + மலர்
வான்முகில் => வான் + முகில்
மதிமணி => மதி + மணி
சுடர்மதி => சுடர் + மதி
மழைவனம் => மழை + வனம்
கதிர்நெல் => கதிர் + நெல்
பூங்கோலம் => பூ + கோலம்
மெல்லடி => மெல் + அடி
பனிவிழி => பனி + விழி
மழைகோடு => மழை + கோடு
மணிகோடு => மணி + கோடு
பெருங்குடி => பெரு + குடி
வான்மணி => வான் + மணி
மலர்வளம் => மலர் + வளம்
காற்றுலகம் => காற்று + உலகம்
சுடர்மகள் => சுடர் + மகள்
பொற்கொடி => பொன் + கொடி
கானமணி => கானம் + மணி
எழிற்கோலம் => எழில் + கோலம்
கனிமலை => கனி + மலை
சுடர்விழி => சுடர் + விழி
நிலக்கோடு => நிலம் + கோடு
சாயமணி => சாயம் + மணி
வெண்குழல் => வெண் + குழல்
கதிரொளி => கதிர் + ஒளி
கமழ்மலர் => கமழ் + மலர்
பொன்மலை => பொன் + மலை
தண்ணீர்நிலை => தண் + நீர் + நிலை
சுடர்கதிர் => சுடர் + கதிர்
அழகிணை => அழகு + இணை
நிழல்மரம் => நிழல் + மரம்
கனிவிழி => கனி + விழி
மழைக்கோலம் => மழை + கோலம்
செந்தேனல் => செம் + தேனல்
கற்பவனம் => கற்பம் + வனம்
சூழ்மலை => சூழ் + மலை
கருங்கதிர் => கரும் + கதிர்
நிலவுக்கோலம் => நிலவு + கோலம்
வேல்மரம் => வேல் + மரம்
கதிர்விழி => கதிர் + விழி
மணிநதி => மணி + நதி
செல்வநதி => செல்வம் + நதி
பூமலர் => பூ + மலர்
வெண்மலர் => வெண் + மலர்
மலர்மணி => மலர் + மணி
செந்தமிழ்மணல் => செம் + தமிழ் + மணல்
எழில்மணி => எழில் + மணி
செழியமலர் => செழியன் + மலர்
மழைவிழி => மழை + விழி
மணிகோலம் => மணி + கோலம்
பனிமலர் => பனி + மலர்
கானமலர் => கானம் + மலர்
சுடர்கோலம் => சுடர் + கோலம்
மணிமலர் => மணி + மலர்
நிலவுபனி => நிலவு + பனி
பனிகோலம் => பனி + கோலம்
நிலவுநதி => நிலவு + நதி
கனிநதி => கனி + நதி
வெண்மணி => வெண் + மணி
பொன்மணி => பொன் + மணி
புயல்கோடு => புயல் + கோடு
காற்றுக்கோடு => காற்று + கோடு
நிலவுதீவு => நிலவு + தீவு
மணிமயில் => மணி + மயில்
புனல்மலை => புனல் + மலை
செம்பொன் => செம் + பொன்
வானமலை => வானம் + மலை
சுடர்வில் => சுடர் + வில்
மணிகொடி => மணி + கொடி
பொற்கதிர் => பொன் + கதிர்
மடல்கோலம் => மடல் + கோலம்
துறவிகோலம் => துறவி + கோலம்
செந்தமிழ்கோலம் => செம் + தமிழ் + கோலம்
செம்பொன்மணி => செம் + பொன் + மணி
கதிர்வேல் => கதிர் + வேல்
சிரமவேல் => சிரம் + வேல்
அருங்கதை => அரும் + கதை
செந்தழல் => செம் + தழல்
சுடர்வனம் => சுடர் + வனம்
பனிகோடு => பனி + கோடு
செழியகோலம் => செழியன் + கோலம்
கடல்கோடு => கடல் + கோடு
மண்கோலம் => மண் + கோலம்
வானிலி => வான் + இலி
செந்தேனீர் => செம் + தேன் + நீர்
சினவிழி => சினம் + விழி
வெண்சுடர் => வெண் + சுடர்
சினமணி => சினம் + மணி
பொற்கோலமணி => பொன் + கோலம் + மணி
பூந்தென்றல் => பூ + தென்றல்
திண்கோலம் => திண் + கோலம்
சுடர்மழை => சுடர் + மழை
மதியொளி => மதி + ஒளி
நிழல்வனம் => நிழல் + வனம்
பொன்மொழி => பொன் + மொழி
கடற்கோலம் => கடல் + கோலம்
வான்கதிர் => வான் + கதிர்
மலர்வனம் => மலர் + வனம்
செந்தீவு => செம் + தீவு
புயல்கதிர் => புயல் + கதிர்
அரும்பொழில் => அரும் + பொழில்
மணித்துளி => மணி + துளி
அரும்பொன் => அரும் + பொன்
செந்தமிழ்வனம் => செம் + தமிழ் + வனம்
பூங்கதிர் => பூ + கதிர்
சிந்தனை => சின்து + அணி
செழியமண் => செழியன் + மண்
மணிமுத்து => மணி + முத்து
நிலாமணி => நிலா + மணி
கதிர்ச்சுடர் => கதிர் + சுடர்
பொன்மயில் => பொன் + மயில்
செங்கதிர் => செம் + கதிர்
அரும்பூ => அரும் + பூ
குருதிநதி => குருதி + நதி
கானகமணி => கானகம் + மணி
புயல்வனம் => புயல் + வனம்
பொற்கோலம் => பொன் + கோலம்
வெண்கதிர் => வெண் + கதிர்
வானமணி => வான் + மணி
மலர்கதிர் => மலர் + கதிர்
மண்விழி => மண் + விழி
கருங்கோடு => கரும் + கோடு
மழைநெல் => மழை + நெல்
நிலவுபூ => நிலவு + பூ
கதிர்பொன் => கதிர் + பொன்
பனிமலை => பனி + மலை
பூமாலை => பூ + மாலை
மழைநிழல் => மழை + நிழல்
சினப்பூ => சினம் + பூ
வான்கொடி => வானம் + கொடி
பொன்மலர் => பொன் + மலர்
மழைப்பெருக்கு => மழை + பெருக்கு
முத்துக்கொடி => முத்து + கொடி
கதிர்நிலா => கதிர் + நிலா
சோலைமணி => சோலை + மணி
பூந்தென் => பூ + தேன்
நிழல்கதிர் => நிழல் + கதிர்
பனிமழை => பனி + மழை
வான்சினம் => வான் + சினம்
புயல்நிழல் => புயல் + நிழல்
கதிர்மதி => கதிர் + மதி
பூந்தோப்பு => பூ + தோப்பு
வான்கோடு => வான் + கோடு
செழியமதி => செழியன் + மதி
பொன்மழை => பொன் + மழை
மணிமழை => மணி + மழை
கதிர்ப்பொழில் => கதிர் + பொழில்
சினவெளி => சினம் + வெளி
நிலாக்கதிர் => நிலா + கதிர்
பனித்துளி => பனி + துளி
மலர்ச்சுடர் => மலர் + சுடர்
செழியமரம் => செழியன் + மரம்
மழைச்சுடர் => மழை + சுடர்
கதிர்மலர் => கதிர் + மலர்
பூந்துளி => பூ + துளி
வான்மழை => வான் + மழை
பொன்விழி => பொன் + விழி
செந்துளி => செம் + துளி
பொன்மதி => பொன் + மதி
சின்மழை => சினம் + மழை
பூமணி => பூ + மணி
பனிச்சுடர் => பனி + சுடர்
மழைக்கதிர் => மழை + கதிர்
மழைப்பூ => மழை + பூ
சுடர்நதி => சுடர் + நதி
மணிமதி => மணி + மதி
பனிமதி => பனி + மதி
வான்நிழல் => வான் + நிழல்
செழியபூ => செழியன் + பூ
சோலைமலர் => சோலை + மலர்
மணிவிழி => மணி + விழி
பொன்கதிர் => பொன் + கதிர்
வான்மதி => வான் + மதி
பூமழை => பூ + மழை
பூவிழி => பூ + விழி
கதிர்ப்பூ => கதிர் + பூ
பூமதி => பூ + மதி
மழைநதி => மழை + நதி
கதிர்மாலை => கதிர் + மாலை
பூம்பொழில் => பூ + பொழில்
மழைக்கொடி => மழை + கொடி
வான்விழி => வான் + விழி
செந்தமிழ்சுடர் => செம் + தமிழ் + சுடர்
பூங்கொடி => பூ + கொடி
செம்மழை => செம் + மழை
கதிர்ப்பொன் => கதிர் + பொன்
மண்நதி => மண் + நதி
நிலவுதுளி => நிலவு + துளி
பூந்தொடி => பூ + தொடி
கதிர்க்கொடி => கதிர் + கொடி
சுடர்கழல் => சுடர் + கழல்
பனிக்கதிர் => பனி + கதிர்
செழியவனம் => செழியன் + வனம்
வானகொடி => வானம் + கொடி
பூவனம் => பூ + வனம்
கதிர்வனம் => கதிர் + வனம்
மழைக்கழல் => மழை + கழல்
சுடர்த்தேன் => சுடர் + தேன்
பூந்தேர் => பூ + தேர்
பனித்தேன் => பனி + தேன்
மணிக்கதிர் => மணி + கதிர்
பூவெண் => பூ + வெண்
பனிவனம் => பனி + வனம்
மழைப்பொழில் => மழை + பொழில்
சுடர்ப்பூ => சுடர் + பூ
செழியநதி => செழியன் + நதி
கதிர்முத்து => கதிர் + முத்து
பூத்துளி => பூ + துளி
மழைப்பொன் => மழை + பொன்
கதிர்த்துளி => கதிர் + துளி
நிலவுக்கதிர் => நிலவு + கதிர்
வான்க்கதிர் => வான் + கதிர்
பூத்தேன் => பூ + தேன்
மண்மலர் => மண் + மலர்
வான்த்துளி => வான் + துளி
நிலாமழை => நிலா + மழை
பூம்பனி => பூ + பனி
கதிர்த்தேன் => கதிர் + தேன்

In [3]:
import csv

asta_file_path = 'punarchi.txt'
out_csv = 'out.csv'

with open(asta_file_path, 'r', encoding='utf-8') as f:
    asta_data = f.readlines()

In [4]:
asta_data[2700]

'கதிர்மேகம் => கதிர் + மேகம்\n'

In [5]:
with open(out_csv, 'w+', newline='', encoding='utf-8') as csvfile:
    csv_writer = csv.writer(csvfile)
    
    csv_writer.writerow(['Text', 'Marked'])

    for line in asta_data:
        text, marked = line.split(' => ')
        csv_writer.writerow([text.strip(), marked.strip()])

In [6]:
import pandas as pd

df = pd.read_csv('out.csv')

df

             Text          Marked
0            பலபல           பல+பல
1          சிலசில         சில+சில
2          பலப்பல           பல+பல
3        சிலச்சில         சில+சில
4          பலற்பல           பல+பல
...           ...             ...
2879      பூதேடல்      பூ + தேடல்
2880     நிலம்பனி     நிலம் + பனி
2881  மலர்விளக்கு  மலர் + விளக்கு
2882    கதிர்பழம்    கதிர் + பழம்
2883      பசுப்பூ        பசு + பூ

[2884 rows x 2 columns]

In [7]:
out_map_csv = 'out_map.csv'

def char_label_mapping(text, labels):
    text_chars = [char_t for char_t in text]
    marked_list = [char_i for char_i in labels]
    result = []
    
    for i, char in enumerate(marked_list):
        if char == "+":
            result.append(' SP')
        else:
            result.append(' NSP')
    
    return ''.join(result)

with open(out_map_csv, 'w', newline='', encoding='utf-8') as csvfile:
    csv_writer = csv.writer(csvfile)
    
    csv_writer.writerow(['Text', 'Marked', 'Labels'])  
    
    for line in asta_data:
        if ' => ' in line:
            text, marked = line.split(' => ')
            print(text.strip())
            print(marked.strip())
            labels = char_label_mapping(text.strip(), marked.strip())
            csv_writer.writerow([text.strip(), marked.strip(), labels])
        else:
            print(f"Skipping line due to incorrect format: {line}")

பலபல
பல+பல
சிலசில
சில+சில
பலப்பல
பல+பல
சிலச்சில
சில+சில
பலற்பல
பல+பல
சிலற்சில
சில+சில
பல்கலை
பல+கலை
பல்சாலை
பல+சாலை
பஃதொடை
பல+தொடை
பன்மலர்
பல+மலர்
பன்னாடு
பல+நாடு
பல்வேண்டி
பல+வேண்டி
பல்லரண்
பல+அரண்
சில்சொல்
சில+சொல்
சின்மலர்
சில+மலர்
சில்வளை
சில+வளை
சில்லணி
சில+அணி
வடகிழக்கு
வடக்கு+கிழக்கு
வடமேற்கு
வடக்கு+மேற்கு
வடவேங்கடம்
வடக்கு+வேங்கடம்
குடதிசை
குடக்கு+திசை
குணதிசை
குணக்கு+திசை
தென்கிழக்கு
தெற்கு+கிழக்கு
தென்மேற்கு
தெற்கு+மேற்கு
தென்குமரி
தெற்கு+குமரி
தென்பாண்டி
தெற்கு+பாண்டி
மேல்காற்று
மேற்கு+காற்று
மேலூர்
மேற்கு+ஊர்
கீழ்கடல்
கிழக்கு+கடல்
கீழ்நாடு
கிழக்கு+நாடு
நல்லன்
நன்மை+அன்
வெண்பட்டு
வெண்மை+பட்டு
வெண்குடை
வெண்மை+குடை
செம்மலர்
செம்மை+மலர்
பெரியன்
பெருமை+அன்
சிறியன்
சிறுமை+அன்
மூதூர்
முதுமை+ஊர்
பாசி
பசுமை+இ
பைங்கொடி
பசுமை+கொடி
பைந்தார்
பசுமை+தார்
சிற்றூர்
சிறுமை+ஊர்
வெற்றிலை
வெறுமை+இலை
வெவ்வேல்
வெம்மை+வேல்
வெந்நீர்
வெம்மை+நீர்
செங்கோல்
செம்மை+கோல்
செந்தமிழ்
செம்மை+தமிழ்
பேரூர்
பெருமை+ஊர்
பைம்பொழில்
பசுமை+பொழில்
தமிழாசிரியர்
தமிழ்+ஆசிரியர்
கடவுளருள்
கடவுள்+அருள்
பொருளனைத்தும்
பொருள்+அனைத்தும்
பூங்கொடி
பூ+கொடி
பூஞ்சோலை
பூ+சோலை
பூந்தோட்டம்
பூ+தோட்டம்
பூம்பாவை
பூ+பாவை
கண்ணொளி
கண்+ஒளி
பண்ணோசை
பண்+ஓசை
மண்ணோசை
மண்+ஓசை
மணியடித்தது
மணி+அடித்தது
தீயெரிந்தது
தீ+எரிந்தது
வாழையிலை
வாழை+இலை
நிலாவழகு
நிலா+அழகு
சேயழகு
சே+அழகு
சேவழகு
சே+அழகு
அந்தப்பையன்
அந்த+பையன்
இந்தப்பெட்டி
இந்த+பெட்டி
அத்துணைப் புகழ்
அத்துணை+புகழ்
இத்துணைச் செழுமை
இத்துணை+செழுமை
எத்துணைக் கொடுமை
எத்துணை+கொடுமை
அவ்வகைக்காடு
அவ்வகை+காடு
இவ்வகைத்தோப்பு
இவ்வகை+தோப்பு
எவ்வகைப்பெயர்
எவ்வகை+பெயர்
மற்றக்கலைகள்
மற்ற+கலைகள்
மற்றுச்சிலை
மற்ற+சிலை
மற்றைப்பயன்
மற்றை+பயன்
மோர்க்குடம்
மோர்+குடம்
மலர்க்கூந்தல்
மலர்+கூந்தல்
தயிர்ப்பானை
தயிர்+பானை
தண்ணீர்த்தொட்டி
தண்ணீர்+தொட்டி
மரப்பெட்டி
மரம்+பெட்டி
இரும்புத்தூண்
இரும்பு+தூண்
தங்கத்தாலி
தங்கம்+தாலி
குடைக்கம்பி
குடை+கம்பி
சட்டைத்துணி
சட்டை+துணி
அடுப்புப்புகை
அடுப்பு+புகை
விழிப்புனல்
விழி+புனல்
புதுக்குடம்
புது+குடம்
வட்டப்பலகை
வட்டம்+பலகை
பொய்ச்செய்தி
பொய்+செய்தி
வேழக்கரும்பு
வேழம்+கரும்பு
தாமரைப்பூ
தாமரை+பூ
மார்கழித்திங்கள்
மார்கழி+திங்கள்
தாமரைக்கண்ணன்
தாமரை+கண்ணன்
பவளச்செவ்வாய்
பவளம்+செவ்வாய்
மலைத்தோள்
மலை+தோள்
அரைக்காணி
அரை+காணி
அரைப்படி
அரை+படி
பாதிப்பங்கு
பாதி+பங்கு
அரைத்தொட்டி
அரை+தொட்டி
பாதிச்செலவு
பாதி+செலவு
திருக்கோவில்
திரு+கோவில்
புதுப்புது
புது+புது
பொதுச்சாலை
பொது+சாலை
வினாக்குறி
வினா+குறி
பலாப்பழம்
பலா+பழம்
கருத்தாய்க்கேட்டாள்
கருத்தாய்+கேட்டாள்
அன்பாய்ச்சொன்னார்
அன்பாய்+சொன்னார்
போய்ப்பார்
போய்+பார்
முன்னர்க்கண்டோம்
முன்னர்+கண்டோம்
பின்னர்க்காண்போம்
பின்னர்+காண்போம்
முன்னர்ச்செல்க
முன்னர்+செல்க
பின்னர்ப்பணிந்தார்
பின்னர்+பணிந்தார்
பட்டுச்சேலை
பட்டு+சேலை
பத்துப்பாட்டு
பத்து+பாட்டு
அவ்வளவுபெரிது
அவ்வளவு+பெரிது
இவ்வளவு கனிவா?
இவ்வளவு+கனிவா
எவ்வளவு தொலைவு?
எவ்வளவு+தொலைவு
அத்தனை புத்தகங்களா?
அத்துணை+புத்தகங்களா
இத்தனை தொழில்களா?
இத்துணை+தொழில்களா
எத்தனை கருவிகள்?
எத்துணை+கருவிகள்
அவனா கேட்டான்?
அவனா+கேட்டான்
அவளா சொன்னாள்?
அவளா+சொன்னாள்
யாரே கண்டார்?
யாரே+கண்டார்
பெரிய பெண்
பெரிய+பெண்
கற்ற சிறுவன்
கற்ற+சிறுவன்
நில்லாத செல்வம்
நில்லாத+செல்வம்
அழியாத கல்வி
அழியாத+கல்வி
ஒன்று கேள்
ஒன்று+கேள்
ஒரு பொருள்
ஒரு+பொருள்
இரண்டு புத்தகம்
இரண்டு+புத்தகம்
இரு பறவை
இரு+பறவை
மூன்று குறிக்கோள்
மூன்று+குறிக்கோள்
நான்கு பேர்
நான்கு+பேர்
ஐந்து கதைகள்
ஐந்து+கதைகள்
ஆறு கோவில்
ஆறு+கோவில்
அறுசீர்
அறு+சீர்
ஏழு சான்றுகள்
ஏழு+சான்றுகள்
எழு பிறப்பு
ஏழு+பிறப்பு
ஒன்பது சுவைகள்
ஒன்பது+சுவைகள்
கலகல
கல+கல
சடசட
சட+சட
பளபள
பள+பள
தீதீ
தீ+தீ
பார்பார்
பார்+பார்
கற்க கசடற
கற்க+கசடற
வெல்க தமிழ்
வெல்க+தமிழ்
வீழ்க தண்புனல்
வீழ்க+தண்புனல்
பல பசு
பல+பசு
சில கலை
சில+கலை
அவை தவித்தன
அவை+தவித்தன
வா கலையரசி
வா+கலையரசி
எழு தம்பி
எழு+தம்பி
போ செல்வி
போ+செல்வி
பார் பெண்ணே
பார்+பெண்ணே
கோவலனோடு கண்ணகி வந்தாள்
கோவலனோடு+கண்ணகி வந்தாள்
துணிவோடு செல்க
துணிவோடு+செல்க
அண்ணனோடு தங்கை வந்தாள்
அண்ணனோடு+தங்கை வந்தாள்
காணிய சென்றேன்
காணிய+சென்றேன்
உண்ணிய சென்றாள்
உண்ணிய+சென்றாள்
தாய் கண்டாள்
தாய்+கண்டாள்
விரிசுடர்
விரி+சுடர்
பாய்புலி
பாய்+புலி
காய்கனி
காய்+கனி
தாய்தந்தை
தாய்+தந்தை
அது பறந்தது
அது+பறந்தது
இது கடித்தது
இது+கடித்தது
எது பறந்தது?
எது+பறந்தது
யாது தந்தார்?
யாது+தந்தார்
கண்ணா பாடு
கண்ணா+பாடு
அண்ணா கேள்
அண்ணா+கேள்
எழுத்துகள்
எழுத்து+கள்
கருத்துகள்
கருத்து+கள்
வாழ்த்துகள்
வாழ்த்து+கள்
போற்றுதல்
போற்று+தல்
நொறுக்குதல்
நொறுக்கு+தல்
கோஷ்டி கானம்
கோஷ்டி+கானம்
சங்கீத சபா
சங்கீத+சபா
வாழைப்பழம்
வாழை+பழம்
மாமரம்
மா+மரம்
அவரைக்காய்
அவரை+காய்
மட்குடம்
மண்+குடம்
மரவேர்
மரம்+வேர்
பெருவள்ளல்
பெருமை+வள்ளல்
பெருநன்மை
பெருமை+நன்மை
மணியழகு
மணி+அழகு
கருத்தோடிசைந்து
கருத்தோடு+இசைந்து
பயணங்கள்
பயணம்+கள்
ஆதாரக்கோடுகள்
ஆதாரம்+கோடுகள்
உருவெடுத்துள்ளன
உருவ+உடுத்துள்ளன
இசைக்கருவி
இசை+கருவி
துளைக்கருவிகள்
துளை+கருவிகள்
சக்கரங்கள்
சக்கர+கள்
கருங்கடல்
கரு+கடல்
நவீனக்கதையாக
நவீன+கதை+ஆக
சிவந்த
சிவப்பு+நடை
இருட்டுக்குள்
இருட்டு+குள்
கரும்புத்
கரும்பு+த்
துயரக்காற்று
துயரம்+காற்று
இயற்பியல்
இயல்+பியல்
கேலக்ஸி
கலை+க்ஸி
கள்ளுக்கடை
கள்ளு+கடை
மதுரக்கள்ளு
மதுரை+க்கள்ளு
பக்கங்கள்
பக்கம்+கள்
இறந்துவிட்ட
இறந்த+விட்ட
இக்கதையை
இந்த+கதை+ஐ
விளக்குகள்
விளக்கு+கள்
ஸிரசாத்தும்
ஸிரசா+த்தும்
இருளில்
இருள்+இல்
பயணித்துக்
பயணம்+இத்து+க
நாடகக்குழு
நாடகம்+குழு
அப்பணசாமி
அப்பன்+சாமி
வள்ளிதிருமணம்
வள்ளி+திருமணம்
நடக்கும்
நட+க்கும்
இலக்கணம்
இலக்கு+ணம்
நாடகக்காரர்கள்
நாடகம்+காரர்கள்
மறந்துபோய்
மறந்த+போய்
நகரும்
நகர்+ும்
இருக்கிறார்கள்
இருக்க+ிறார்கள்
பயணித்த
பயணம்+இத்து
கிழக்கில்
கிழக்கு+இல்
பக்கத்தில்
பக்கம்+இல்
சீறிவரும்
சீறும்+வரும்
ஊருமே
ஊர்+உமே
இறந்துபோன
இறந்த+போன
குழந்தையின்
குழந்தை+இன்
ஒன்றுகலந்து
ஒன்று+கலந்து
அக்கார்டியன்
அக்கார்ட்+டியன்
கந்தசாமி
கந்த+சாமி+இன்
வெளிவந்த
வெளியே+வந்த
பாட்டக்குளம்
பாட்டு+குளம்
இருமுனை
இரு+முனை
இயற்கையின்
இயற்கை+இன்
மயக்கமுறும்
மயக்கம்+முறும்
இயலாமையின்
இயலாமை+இன்
உருக்கம்
உரு+க்கம்
சரவணக்குமார்
சரவணன்+குமார்
கிடக்கும்
கிடைக்க+ும்
இருக்கும்
இருக்க+ும்
இக்கதை
இந்த+கதை
இருட்டு
இருள்+ட்டு
ஜெயந்தன்
ஜெய+ந்தன்
வந்துசெல்கிறது
வந்த+செல்கிறது
ஜெயந்தனின்
ஜெயந்தன்+இன்
வரும்
வர+ும்
இருவர்
இரு+வர
இருந்துவரும்
இருந்த+வரும்
சம்பந்தமில்லாமல்
சம்பந்த+மில்லாமல்
இருந்தது
இருந்த+து
மையமிழந்து
மையம்+அழந்து
கணக்கியலை
கணக்கு+கலை
சந்தித்துக்கொண்ட
சந்தி+த்துக்கொண்ட
சந்தர்ப்பங்கள்
சந்தர்ப்பு+கள்
உருமாறி
உரு+மாறி
கொலைவழக்கு
கொலை + வழக்கு
வெளிவந்த
வெளி + வந்த
விளக்கைச்
விளக்கு + இச்
இறக்கைகள்
இறக்கு + கைகள்
இருப்பில்
இருப்பு + இல்
இருள்
இருள் + டைப்
துலக்கமான
துலக்கம் + மான
வந்துவிட்டான்
வந்த + விட்டான்
அந்நியமான
அந்நிய + மான
இருந்தார்கள்
இருந்த + அர்கள்
இருக்கிறது
இருக்க + இரு
சிலந்தியின்
சிலந்தி + இன்
பலாச்சுளை
பலா+சுளை
படக்காட்சி
படம்+காட்சி
பொற்சிலை
பொன்+சிலை
பொன்வளையல்
பொன்+வளையல்
கண்ணழகு
கண்+அழகு
மலர்மாலை
மலர்+மாலை
பனைமரம்
பனை+மரம்
மரவேர்
மரம் + வேர்
செந்தமிழ்
செம் + தமிழ்
பஞ்சகத்தி
பஞ்சம் + கத்தி
மெய்யாளர்
மெய் + யாளர்
பழநீர்
பழம் + நீர்
நிலவழி
நிலம் + வழி
வாழ்விடம்
வாழ்வு + இடம்
சிந்தனை
சிது + தனை
அருங்காட்சி
அரும் + காட்சி
காவலர்
காவல் + லர்
வேறுபாடு
வேறு + பாடு
கண்ணோட்டம்
கண் + நோட்டம்
நீர்வளம்
நீர் + வளம்
நூலாளர்
நூல் + ஆலர்
தங்கம்
தன் + கம்
காய்ச்சல்
காய் + ச்சல்
பாசமயம்
பாசம் + அயம்
தேசாந்திரி
தேசம் + அந்திரி
நல்லாசி
நல் + ஆசி
சிற்றறிவு
சிறு + அறிவு
உள்ளகம்
உள் + லகம்
கனல்நீர்
கனல் + நீர்
சூழ்வளம்
சூழ் + வளம்
வணிகர்
வணிகம் + இர்
புணர்ச்சி
புணர் + ச்சி
வடநாடு
வட + நாடு
பொன்னுலகம்
பொன் + உலகம்
மாடுவாசல்
மாடு + வாசல்
கடல்சாரம்
கடல் + சாரம்
கலந்துரை
கலந்து + உரை
பாடல்சாரம்
பாடல் + சாரம்
வானவெளி
வானம் + வெளி
வீரமணி
வீரம் + மணி
மணியாரும்
மணி + ஆரும்
திடம்கொள்
திடம் + கொள்
புத்தகவாசி
புத்தகம் + வாசி
நூற்காட்சி
நூல் + காட்சி
முரசோலி
முரசு + ஓலி
வேளாண்மை
வேளை + ஆண்மை
செல்வமுறை
செல்வம் + முறை
இலக்கியம்
இலக்கு + இயம்
காதல்மொழி
காதல் + மொழி
அழகுருவி
அழகு + உருவி
பொற்கதை
பொன் + கதை
கொடையரசு
கொடை + அரசு
பணியாளன்
பணி + ஆளன்
விலங்கியல்
விலங்கு + இயல்
விழியார்
விழி + யார்
மண்ணமர்
மண் + அமர்
சாந்தியாழி
சாந்தி + ஆழி
கடல்நகர்
கடல் + நகர
நாட்டியக் கலை
நாட்டியம் + கலை
நிலவந்தி
நிலம் + அந்தி
கூழ்நீர்மை
கூழ் + நீர்மை
சிற்றொழுகு
சிறு + ஒழுகு
முடிவுரை
முடிவு + உரை
சபாநாயகர்
சபை + நாயகர்
வணங்கல்
வணங்கு + அல்
சுயமரியாதை
சுயம் + மரியாதை
கழகத் தலைவர்
கழகம் + தலைவர்
பருவநிலை
பருவம் + நிலை
பசுமைநிலம்
பசுமை + நிலம்
உழவர்மணி
உழவர் + மணி
திரையரங்கு
திரை + அரங்கு
பொன்மாலை
பொன் + மாலை
கவிதைவளம்
கவிதை + வளம்
கவிதைநூல்
கவிதை + நூல்
மரமோடு
மரம் + ஓடு
சந்தனக்கால்
சந்தனம் + காலை
தமிழ்ச் சொல்
தமிழ் + சொல்
தென்னமுது
தென்னம் + முது
கற்கோலம்
கல் + கோலம்
கொடியருவி
கொடி + அருவி
செம்மரம்
செம் + மரம்
நிலவுசுடர்
நிலவு + சுடர்
சொற்பழம்
சொல் + பழம்
நறும்பூ
நறும் + பூ
குடிமகன்
குடி + மகன்
வளம்நிலம்
வளம் + நிலம்
மானுடவளம்
மானுடம் + வளம்
மின்சாரம்
மின் + சாரம்
குமிழ்நீர்
குமிழ் + நீர்
புதுமணம்
புது + மணம்
குடிசொல்
குடி + சொல்
உயிர்வளி
உயிர் + வளி
இலவசநீர்
இலவசம் + நீர்
வள்ளுவர்
வள்ளு + அவர்
சிந்தாமணி
சிந்தை + மணி
வெள்ளநீர்
வெள்ளம் + நீர்
வானளி
வானம் + அளி
கூந்தல்
கூந் + தல்
குளிர்ந்தலை
குளிர் + தலைய
வடசெல்வம்
வட + செல்வம்
அமிழ்தமோர்
அமிழ்தம் + ஓர்
பந்தல்
பந்தம் + அல்
குளம்பேர்
குளம் + பேர்
மாயவரம்
மாயம் + வரம்
அசைவகம்
அசை + வகம்
பற்பலம்
பல + பலம்
வருங்காலம்
வரும் + காலம்
கற்பகமரம்
கற்பகம் + மரம்
நெடுநாள்
நெடு + நாள்
சுடரொளி
சுடர் + ஒளி
ஆற்றொழில்
ஆற்று + தொழில்
பொற்கோவில்
பொன் + கோவில்
வேளாண்
வேலை + ஆண்
மண்ணிடு
மண் + இடு
கதிரோன்
கதிர் + ஓன்
பொருளாதாரம்
பொருள் + ஆதாரம்
பாடசாலை
பாடம் + சாலை
சோலையடை
சோலை + அடை
கொடிக்கொடி
கொடி + கொடி
சிற்றரசு
சிறு + அரசு
கடலோரம்
கடல் + ஓரம்
தென்றல்
தென் + தல்
வீரவிழா
வீரம் + விழா
உணவகம்
உணவு + அகம்
நிழல்வேல்
நிழல் + வேல்
மகிழ்ச்சி
மகிழ் + ச்சி
தங்கவேல்
தங்கம் + வேல்
பிள்ளையார்
பிள்ளை + யார்
மணிமொழி
மணி + மொழி
மணிக்கோல்
மணி + கோல்
வெண்ணெய்
வெண் + நெய்
வானவில்
வானம் + வில்
கொடியிலங்கு
கொடி + இலம் + இங்கு
மரபு வழி
மரபு + வழி
மலர்க்கொடி
மலர் + கொடி
மெய்ப்பொருள்
மெய் + பொருள்
வானொலி
வான் + ஒலி
முத்தமிழ்
முத் + தமிழ்
நுண்கலை
நுண் + கலை
கதிர்கோள்
கதிர் + கோள்
உடனடி
உடன் + அடி
விருட்சம்
விரு + ச்சம்
கலந்தகூட்டம்
கலந்து + கூட்டம்
பரந்தகோலம்
பரந்து + கோலம்
நெடும்பால்
நெடு + பால்
அகிலநிலை
அகிலம் + நிலை
சுவையமை
சுவை + அமை
காற்று நடை
காற்று + நடை
நல்லிணக்கம்
நல் + இணக்கம்
உறவுநிலை
உறவு + நிலை
சாய்க்கோலம்
சாய்க்கு + கோலம்
நிலவறிவு
நிலவு + அறிவு
பொறியியல்
பொறி + இயல்
பணிநிலை
பணி + நிலை
முற்றுமனை
முறை + மனை
நூறாண்டு
நூறு + ஆண்டு
பண்பாளர்
பண்பு + ஆளர்
சீர்திருத்தம்
சீர் + திருத்தம்
வாழ்நிலை
வாழ் + நிலை
மின்வெள்ளம்
மின் + வெள்ளம்
பூமகள்
பூ + மகள்
மனவளம்
மனம் + வளம்
கால்சட்டை
கால் + சட்டை
மாணாக்கர்
மாண் + ஆக்கர்
மலர்ந்தது
மலர் + இந்து
சீதோஷணம்
சீ + தோஷணம்
கடலவன்
கடல் + அவன்
இலக்கணம்
இலக்கு + அணம
தீர்ப்பாசி
தீர்ப்ப + ஆசி
மதிநிலா
மதிலிலா
மன்னவள்
மன்னன் + அவள்
பூங்கொத்து
பூ + கொத்து
மேகமண்டலம்
மேகம் + மண்டலம்
விளக்கொளி
விளக்கு + ஒளி
கதிர்மணி
கதிர் + மணி
பருவமழை
பருவம் + மழை
செந்தோப்பு
செம் + தோப்பு
பேரழகு
பெரு + அழகு
இனியசொல்
இனிய + சொல்
கொடிமரம்
கொடி + மரம்
வான்குடில்
வான் + குடில்
பொற்காலம்
பொன் + காலம்
சுடர்மணி
சுடர் + மணி
நிலமடி
நிலம் + அடி
வெண்மதி
வெண் + மதி
சிற்பகலை
சிற்பம் + கலை
மழைத்துளி
மழை + துளி
சூரியகிரணம்
சூரியன் + கிரணம்
காவேரிநதி
காவிரி + நதி
புத்தர்மலை
புத்தர் + மலை
இனியமனம்
இனிய + மனம்
அடையாளமணி
அடையாளம் + மணி
காவல்துறை
காவல் + துறை
வானவரம்பு
வானம் + வரம்பு
பழமொழி
பழம் + மொழி
முள்ளாங்கொடி
முள்ளான் + கொடி
பனைமரம்
பனை + மரம்
குருதியெழுத்து
குருதி + எழுத்து
படர்கதிர்
படர் + கதிர்
அறிவாளர்
அறிவு + ஆளர்
அன்பரசு
அன்பு + அரசு
ஆறுமுகம்
ஆறு + முகம்
சாந்தவனம்
சாந்தம் + வனம்
நிலமொழி
நிலம் + மொழி
சிறுபிள்ளை
சிறு + பிள்ளை
முத்தானம்
முத்து + ஆனம்
நூல்நயம்
நூல் + நயம்
சோலைமலை
சோலை + மலை
மரம்கொடி
மரம் + கொடி
நிலவொளி
நிலவு + ஒளி
மழைக்கோல்
மழை + கோல்
காற்றுநிலை
காற்று + நிலை
கனிவொளி
கனி + ஒளி
சூரியபாதை
சூரியன் + பாதை
கடல்நுரை
கடல் + நுரை
அறம்வழி
அறம் + வழி
கானல்நிலம்
கானல் + நிலம்
மணியாடை
மணி + ஆடை
செல்வநிலை
செல்வம் + நிலை
பொற்கோடை
பொன் + கோடை
நிலத்தடி
நிலம் + அடி
வாழ்வெழுச்சி
வாழ்வு + எழுச்சி
புதல்வர்
புதல் + வர
புயல்வேகம்
புயல் + வேகம்
சுவைநிலை
சுவை + நிலை
நெஞ்சுரம்
நெஞ்சு + உரம்
இரவுநதி
இரவு + நதி
கலைவளம்
கலை + வளம்
மால்வரை
மால் + வரை
செழியமணி
செழியன் + மணி
கருங்காலி
கரும் + காலி
விளக்குரை
விளக்கு + உரை
காற்றுவளம்
காற்று + வளம்
பழங்கதை
பழம் + கதை
பொற்குழல்
பொன் + குழல்
எழுத்தாளன்
எழுத்து + ஆளன்
கண்ணிழிவு
கண் + இழிவு
தெய்வகதை
தெய்வம் + கதை
அரும்படி
அரும் + படி
ஊர்நிலை
ஊர் + நிலை
மணிச்சுடர்
மணி + சுடர்
செழும்பாடு
செழும் + பாடு
வான்நிலம்
வான் + நிலம்
கனிமொழி
கனி + மொழி
பழனிவேல்
பழனி + வேல்
அமிழ்தாறு
அமிழ்து + ஆறு
வேல்மணி
வேல் + மணி
மருந்தகம்
மருந்து + அகம்
சின்மொழி
சினம் + மொழி
வெறியாள்
வெறி + யாள்
கொடிமாடம்
கொடி + மாடம்
நட்சத்திரவளம்
நட்சத்திரம் + வளம்
மெய்வழி
மெய் + வழி
கதிர்நிழல்
கதிர் + நிழல்
மணியொளி
மணி + ஒளி
செம்மொழி
செம் + மொழி
செம்மணி
செம் + மணி
கடல்படை
கடல் + படை
திருக்கோவில்
திரு + கோவில்
சுடர்மலை
சுடர் + மலை
நளினமணி
நளினம் + மணி
வரலாற்று
வரல் + ஆறு
சீர்மிகு
சீரு + மிகு
பாற்குடம்
பால் + குடம்
செந்தேன்
செம் + தேன்
மண்ணொலி
மண் + ஒலி
விளங்கோலம்
விளம் + கோலம்
மூங்கில்
மூ + கில்
அறந்தலம்
அறம் + தலம்
முல்லைப்பூ
முல்லை + பூ
காற்றுமரம்
காற்று + மரம்
வெள்ளவெண்
வெள்ளம் + வெண்
கடல்சங்கு
கடல் + சங்கு
மண்ணோடு
மண் + ஓடு
உலோகவேல்
உலோகம் + வேல்
பசும்விழி
பசு + விழி
வெண்கோல்
வெண் + கோல்
மண்ணிறம்
மண் + நிறம்
கொடிமலை
கொடி + மலை
கலைமகள்
கலை + மகள்
வண்ணக்குடை
வண்ணம் + குடை
மருந்துவேர்
மருந்து + வேர்
மண்ணறை
மண் + அறை
ஆரண்மனை
ஆரம் + மனை
சுடர்கோல்
சுடர் + கோல்
கொன்றைவனம்
கொன்றை + வனம்
வான்கோலம்
வானம் + கோலம்
கானகத்தேர்
கானகம் + தேர்
கடல்மணி
கடல் + மணி
முற்றவறை
முறை + அறை
வான்சுடர்
வானம் + சுடர்
இருள்வழி
இருள் + வழி
காற்றுவழி
காற்று + வழி
செறியடி
செறி + அடி
குருதிமணல்
குருதி + மணல்
கருங்கூடு
கரும் + கூடு
கனவுயர்வு
கனவு + உயர்வு
எழில்கனி
எழில் + கனி
மருங்கணி
மருங்கு + அணி
மலைவழி
மலை + வழி
கடல்மலை
கடல் + மலை
கதிர்மழை
கதிர் + மழை
மழைமணி
மழை + மணி
பசும்பொன்
பசு + பொன்
மழைத்தேன்
மழை + தேன்
செம்மலர்
செம் + மலர்
வான்முகில்
வான் + முகில்
மதிமணி
மதி + மணி
சுடர்மதி
சுடர் + மதி
மழைவனம்
மழை + வனம்
கதிர்நெல்
கதிர் + நெல்
பூங்கோலம்
பூ + கோலம்
மெல்லடி
மெல் + அடி
பனிவிழி
பனி + விழி
மழைகோடு
மழை + கோடு
மணிகோடு
மணி + கோடு
பெருங்குடி
பெரு + குடி
வான்மணி
வான் + மணி
மலர்வளம்
மலர் + வளம்
காற்றுலகம்
காற்று + உலகம்
சுடர்மகள்
சுடர் + மகள்
பொற்கொடி
பொன் + கொடி
கானமணி
கானம் + மணி
எழிற்கோலம்
எழில் + கோலம்
கனிமலை
கனி + மலை
சுடர்விழி
சுடர் + விழி
நிலக்கோடு
நிலம் + கோடு
சாயமணி
சாயம் + மணி
வெண்குழல்
வெண் + குழல்
கதிரொளி
கதிர் + ஒளி
கமழ்மலர்
கமழ் + மலர்
பொன்மலை
பொன் + மலை
தண்ணீர்நிலை
தண் + நீர் + நிலை
சுடர்கதிர்
சுடர் + கதிர்
அழகிணை
அழகு + இணை
நிழல்மரம்
நிழல் + மரம்
கனிவிழி
கனி + விழி
மழைக்கோலம்
மழை + கோலம்
செந்தேனல்
செம் + தேனல்
கற்பவனம்
கற்பம் + வனம்
சூழ்மலை
சூழ் + மலை
கருங்கதிர்
கரும் + கதிர்
நிலவுக்கோலம்
நிலவு + கோலம்
வேல்மரம்
வேல் + மரம்
கதிர்விழி
கதிர் + விழி
மணிநதி
மணி + நதி
செல்வநதி
செல்வம் + நதி
பூமலர்
பூ + மலர்
வெண்மலர்
வெண் + மலர்
மலர்மணி
மலர் + மணி
செந்தமிழ்மணல்
செம் + தமிழ் + மணல்
எழில்மணி
எழில் + மணி
செழியமலர்
செழியன் + மலர்
மழைவிழி
மழை + விழி
மணிகோலம்
மணி + கோலம்
பனிமலர்
பனி + மலர்
கானமலர்
கானம் + மலர்
சுடர்கோலம்
சுடர் + கோலம்
மணிமலர்
மணி + மலர்
நிலவுபனி
நிலவு + பனி
பனிகோலம்
பனி + கோலம்
நிலவுநதி
நிலவு + நதி
கனிநதி
கனி + நதி
வெண்மணி
வெண் + மணி
பொன்மணி
பொன் + மணி
புயல்கோடு
புயல் + கோடு
காற்றுக்கோடு
காற்று + கோடு
நிலவுதீவு
நிலவு + தீவு
மணிமயில்
மணி + மயில்
புனல்மலை
புனல் + மலை
செம்பொன்
செம் + பொன்
வானமலை
வானம் + மலை
சுடர்வில்
சுடர் + வில்
மணிகொடி
மணி + கொடி
பொற்கதிர்
பொன் + கதிர்
மடல்கோலம்
மடல் + கோலம்
துறவிகோலம்
துறவி + கோலம்
செந்தமிழ்கோலம்
செம் + தமிழ் + கோலம்
செம்பொன்மணி
செம் + பொன் + மணி
கதிர்வேல்
கதிர் + வேல்
சிரமவேல்
சிரம் + வேல்
அருங்கதை
அரும் + கதை
செந்தழல்
செம் + தழல்
சுடர்வனம்
சுடர் + வனம்
பனிகோடு
பனி + கோடு
செழியகோலம்
செழியன் + கோலம்
கடல்கோடு
கடல் + கோடு
மண்கோலம்
மண் + கோலம்
வானிலி
வான் + இலி
செந்தேனீர்
செம் + தேன் + நீர்
சினவிழி
சினம் + விழி
வெண்சுடர்
வெண் + சுடர்
சினமணி
சினம் + மணி
பொற்கோலமணி
பொன் + கோலம் + மணி
பூந்தென்றல்
பூ + தென்றல்
திண்கோலம்
திண் + கோலம்
சுடர்மழை
சுடர் + மழை
மதியொளி
மதி + ஒளி
நிழல்வனம்
நிழல் + வனம்
பொன்மொழி
பொன் + மொழி
கடற்கோலம்
கடல் + கோலம்
வான்கதிர்
வான் + கதிர்
மலர்வனம்
மலர் + வனம்
செந்தீவு
செம் + தீவு
புயல்கதிர்
புயல் + கதிர்
அரும்பொழில்
அரும் + பொழில்
மணித்துளி
மணி + துளி
அரும்பொன்
அரும் + பொன்
செந்தமிழ்வனம்
செம் + தமிழ் + வனம்
பூங்கதிர்
பூ + கதிர்
சிந்தனை
சின்து + அணி
செழியமண்
செழியன் + மண்
மணிமுத்து
மணி + முத்து
நிலாமணி
நிலா + மணி
கதிர்ச்சுடர்
கதிர் + சுடர்
பொன்மயில்
பொன் + மயில்
செங்கதிர்
செம் + கதிர்
அரும்பூ
அரும் + பூ
குருதிநதி
குருதி + நதி
கானகமணி
கானகம் + மணி
புயல்வனம்
புயல் + வனம்
பொற்கோலம்
பொன் + கோலம்
வெண்கதிர்
வெண் + கதிர்
வானமணி
வான் + மணி
மலர்கதிர்
மலர் + கதிர்
மண்விழி
மண் + விழி
கருங்கோடு
கரும் + கோடு
மழைநெல்
மழை + நெல்
நிலவுபூ
நிலவு + பூ
கதிர்பொன்
கதிர் + பொன்
பனிமலை
பனி + மலை
பூமாலை
பூ + மாலை
மழைநிழல்
மழை + நிழல்
சினப்பூ
சினம் + பூ
வான்கொடி
வானம் + கொடி
பொன்மலர்
பொன் + மலர்
மழைப்பெருக்கு
மழை + பெருக்கு
முத்துக்கொடி
முத்து + கொடி
கதிர்நிலா
கதிர் + நிலா
சோலைமணி
சோலை + மணி
பூந்தென்
பூ + தேன்
நிழல்கதிர்
நிழல் + கதிர்
பனிமழை
பனி + மழை
வான்சினம்
வான் + சினம்
புயல்நிழல்
புயல் + நிழல்
கதிர்மதி
கதிர் + மதி
பூந்தோப்பு
பூ + தோப்பு
வான்கோடு
வான் + கோடு
செழியமதி
செழியன் + மதி
பொன்மழை
பொன் + மழை
மணிமழை
மணி + மழை
கதிர்ப்பொழில்
கதிர் + பொழில்
சினவெளி
சினம் + வெளி
நிலாக்கதிர்
நிலா + கதிர்
பனித்துளி
பனி + துளி
மலர்ச்சுடர்
மலர் + சுடர்
செழியமரம்
செழியன் + மரம்
மழைச்சுடர்
மழை + சுடர்
கதிர்மலர்
கதிர் + மலர்
பூந்துளி
பூ + துளி
வான்மழை
வான் + மழை
பொன்விழி
பொன் + விழி
செந்துளி
செம் + துளி
பொன்மதி
பொன் + மதி
சின்மழை
சினம் + மழை
பூமணி
பூ + மணி
பனிச்சுடர்
பனி + சுடர்
மழைக்கதிர்
மழை + கதிர்
மழைப்பூ
மழை + பூ
சுடர்நதி
சுடர் + நதி
மணிமதி
மணி + மதி
பனிமதி
பனி + மதி
வான்நிழல்
வான் + நிழல்
செழியபூ
செழியன் + பூ
சோலைமலர்
சோலை + மலர்
மணிவிழி
மணி + விழி
பொன்கதிர்
பொன் + கதிர்
வான்மதி
வான் + மதி
பூமழை
பூ + மழை
பூவிழி
பூ + விழி
கதிர்ப்பூ
கதிர் + பூ
பூமதி
பூ + மதி
மழைநதி
மழை + நதி
கதிர்மாலை
கதிர் + மாலை
பூம்பொழில்
பூ + பொழில்
மழைக்கொடி
மழை + கொடி
வான்விழி
வான் + விழி
செந்தமிழ்சுடர்
செம் + தமிழ் + சுடர்
பூங்கொடி
பூ + கொடி
செம்மழை
செம் + மழை
கதிர்ப்பொன்
கதிர் + பொன்
மண்நதி
மண் + நதி
நிலவுதுளி
நிலவு + துளி
பூந்தொடி
பூ + தொடி
கதிர்க்கொடி
கதிர் + கொடி
சுடர்கழல்
சுடர் + கழல்
பனிக்கதிர்
பனி + கதிர்
செழியவனம்
செழியன் + வனம்
வானகொடி
வானம் + கொடி
பூவனம்
பூ + வனம்
கதிர்வனம்
கதிர் + வனம்
மழைக்கழல்
மழை + கழல்
சுடர்த்தேன்
சுடர் + தேன்
பூந்தேர்
பூ + தேர்
பனித்தேன்
பனி + தேன்
மணிக்கதிர்
மணி + கதிர்
பூவெண்
பூ + வெண்
பனிவனம்
பனி + வனம்
மழைப்பொழில்
மழை + பொழில்
சுடர்ப்பூ
சுடர் + பூ
செழியநதி
செழியன் + நதி
கதிர்முத்து
கதிர் + முத்து
பூத்துளி
பூ + துளி
மழைப்பொன்
மழை + பொன்
கதிர்த்துளி
கதிர் + துளி
நிலவுக்கதிர்
நிலவு + கதிர்
வான்க்கதிர்
வான் + கதிர்
பூத்தேன்
பூ + தேன்
மண்மலர்
மண் + மலர்
வான்த்துளி
வான் + துளி
நிலாமழை
நிலா + மழை
பூம்பனி
பூ + பனி
கதிர்த்தேன்
கதிர் + தேன்
செழியவிழி
செழியன் + விழி
நிலவுமதி
நிலவு + மதி
செந்தேர்
செம் + தேர்
பூங்கழல்
பூ + கழல்
செழியமலை
செழியன் + மலை
சுடர்த்துளி
சுடர் + துளி
நிலாமலர்
நிலா + மலர்
பூநதி
பூ + நதி
நேயெனக்கு
நீ + எனக்கு
அதெந்த
அது + எந்த
இலையது
இலை + அது
கலையிலக்கு
கலை + இலக்கு
மேயங்கு
மே + இங்கு
நமூர்
நம் + ஊர்
இதாங்கு
இது + அங்கு
உனறம்
உன் + அறம்
எமுரை
எம் + உரை
இவளாகும்
இவள் + ஆகும்
அவனன்றான்
அவன் + என்றான்
அவருதவி
அவர் + உதவி
கையெடுத்தல்
கை + எடுத்தல்
சாரிடம்
சார் + இடம்
இதுஏன்
இது + ஏன்
போயெங்கே
போ + எங்கே
எதுவாகும்
எது + ஆகும்
நானடைவேன்
நான் + அடைவேன்
நீயேன்
நீ + ஏன்
அதிங்கே
அது + இங்கே
அதுவவன்
அது + அவன்
அவரொப்பனை
அவர் + ஒப்பனை
இதொவ்வொரு
இது + ஒவ்வொரு
உனூக்கம்
உன் + ஊக்கம்
அவனங்கு
அவன் + அங்கு
உள்ளிடம்
உள் + இடம்
கீழூர்
கீழ் + ஊர்
மேலடி
மேல் + அடி
கையாடு
கை + ஆடு
கதையது
கதை + இது
வழியிருக்கிறது
வழி + இருக்கிறது
நீரலை
நீர் + அலை
அடியுதவியாளர்
அடி + உதவியாளர்
இலையுதவி
இலை + உதவி
சோறேந்தி
சோறு + ஏந்தி
மழையடி
மழை + அடி
பசியடக்குதல்
பசி + அடக்குதல்
நீயொப்புதல்
நீ + ஒப்புதல்
தாயுண்மை
தாய் + உண்மை
தேரெழுத்து
தேர் + எழுத்து
கண்ண்பிடி
கண் + பிடி
பத்தெரு
பல் + தெரு
பூங்கதை
பூஞ் + கதை
சொன்னூல்
சொல் + நூல்
விளைப்பசி
விளை + பசி
ஆண்பெயர்
ஆள் + பெயர்
கூர்பசி
கூழ் + பசி
பற்காய்
பல் + காய்
செம்பசி
செம் + பசி
கற்பாறை
கல் + பாறை
மண்ண்குளம்
மண் + குளம்
புன்னூல்
புன் + நூல்
வாள்படை
வாள் + படை
தென்பக்கம்
தென் + பக்கம்
தண்காற்று
தண் + காற்று
தண்பனி
தண் + பனி
மண்டிரண்டு
மண் + திரண்டு
கள்மூட்டுக்
கல் + மூட்டுக்
பழம்பொதி
பழம் + பொதி
வண்கூடு
வண் + கூடு
கண்ண்புரை
கண் + புரை
பல்வீடு
பல் + வீடு
செம்போர்
செம் + போர்
புட்பறவை
புள் + பறவை
தொன்கதை
தொல் + கதை
தள்குணம்
தள் + குணம்
நீள்பறவை
நீள் + பறவை
ஆண்பணி
ஆள் + பணி
பற்கதை
பல் + கதை
வாள்பாய்ச்சி
வாள் + பாய்ச்சி
கற்பிளவு
கல் + பிளவு
வண்கதிர்
வண் + கதிர்
மண்ண்பயிர்
மண் + பயிர்
கண்ண்புண்ணி
கண் + புண்ணி
வாள்பாடல்
வாள் + பாடல்
மேபார்
மே + பார்
நீபோ
நீ + போ
அதுசுமை
அது + சுமை
இங்குபோ
இங்கு + போ
நான்சொல்
நான் + சொல்
அதுதொடர்
அது + தொடர்
எதுபரிசு
எது + பரிசு
அதுகதவு
அது + கதவு
நீநட
நீ + நட
அதுபயணம்
அது + பயணம்
மேகொடி
மே + கொடி
நீபக்கம்
நீ + பக்கம்
அதுவழி
அது + வழி
இதுபயிர்
இது + பயிர்
எதுதெரு
எது + தெரு
நான்பணம்
நான் + பணம்
இதுமுடி
இது + முடி
நீபெயர்
நீ + பெயர்
எங்குபோ
எங்கு + போ
அதுபலம்
அது + பலம்
நீதேர்வு
நீ + தேர்வு
அதுபாடம்
அது + பாடம்
எதுவலை
எது + வலை
இதுகதை
இது + கதை
நீமுன்
நீ + முன்
மாபல்
மா + பல்
தேர்வரை
தேர் + வரை
போர்கடல்
போர் + கடல்
சோறுபழம்
சோறு + பழம்
வாரிகெடுதல்
வாரி + கெடுதல்
வீடுபடி
வீடு + படி
ஓடுசுழல்
ஓடு + சுழல்

In [8]:
 import pandas
 dataframe_df = pandas.read_csv('out_map.csv')
 
 dataframe_df

,Text,Marked,Labels
0,பலபல,பல+பல,NSP NSP SP NSP NSP
1,சிலசில,சில+சில,NSP NSP NSP SP NSP NSP NSP
2,பலப்பல,பல+பல,NSP NSP SP NSP NSP
3,சிலச்சில,சில+சில,NSP NSP NSP SP NSP NSP NSP
4,பலற்பல,பல+பல,NSP NSP SP NSP NSP
...,...,...,...
2879,பூதேடல்,பூ + தேடல்,NSP NSP NSP SP NSP NSP NSP NSP NSP NSP
2880,நிலம்பனி,நிலம் + பனி,NSP NSP NSP NSP NSP NSP SP NSP NSP NSP NSP
2881,மலர்விளக்கு,மலர் + விளக்கு,NSP NSP NSP NSP NSP SP NSP NSP NSP NSP NSP NS...
2882,கதிர்பழம்,கதிர் + பழம்,NSP NSP NSP NSP NSP NSP SP NSP NSP NSP NSP NSP
2883,பசுப்பூ,பசு + பூ,NSP NSP NSP NSP SP NSP NSP NSP

In [9]:
with open('punarchi_mapped.txt', 'w+') as f:
    lines = []
    for i in range(dataframe_df.shape[0]):
        lines.append(dataframe_df['Text'][i] + dataframe_df['Labels'][i] + '\n')
    f.writelines(lines)